displayName: Statiq
type: middleware
iconPath: .assets/icon.png

import: github.com/hhftechnology/statiq

summary: 'A feature-rich static file server inside Traefik'

testData:
  root: /var/www/html/
  enableDirectoryListing: false
  indexFiles:
    - index.html
    - index.htm
  spaMode: false
  spaIndex: index.html
  errorPage404: ""
  cacheControl:
    ".html": "max-age=3600"
    ".css": "max-age=86400"
    ".js": "max-age=86400"
    "*": "max-age=3600"